server.port=8085
spring.application.name=api-gateway
spring.main.web-application-type=reactive

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=api-gateway:8080

# This is the key fix - tells actuator to report UP status to Eureka
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

jwt.secret=${JWT_SECRET}

# JOB SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=job-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://JOB-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/jobs/**


# AUTH SERVICE (NO FILTER)
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**

## APPLICATION SERVICE
#spring.cloud.gateway.server.webflux.routes[2].id=application-service
#spring.cloud.gateway.server.webflux.routes[2].uri=lb://APPLICATION-SERVICE
#spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/applications/**


## ADMIN SERVICE
#spring.cloud.gateway.server.webflux.routes[3].id=admin-service
#spring.cloud.gateway.server.webflux.routes[3].uri=lb://ADMIN-SERVICE
#spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/admin/**
